config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  root 'welcome#index'
    get '/about' => 'about#index'
    # get '/terms' => 'terms#index'
    get '/faq' => 'faq#index'
    get '/tasks' => 'tasks#index'
    get '/users' => 'users#index'
    get '/projects' => 'projects#index'
    get '/projects/:id/noaccess' => 'projects#redirect_for_non_member'

    get '/signup' => 'registrations#new'
    post '/signup' => 'registrations#create'

    get '/signin' => 'sessions#new'
    post '/signin' => 'sessions#create'

    get '/signout' => 'sessions#destroy'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user_id, :role, presence: true
  validates_uniqueness_of :user_id, :scope => :project_id, message: "has already been added to this project."

end

app/controllers/memberships_controller.rb
 class MembershipsController < ApplicationController

  before_action :authenticate
  before_action :set_project
  before_action :set_membership, only: [:update, :destroy]
  before_action :check_last_owner, only: [:update]
  before_action :remove_action_authentication
  before_action :role_authentication, only: [:update]
  before_action :member_authentication

  def index
    @membership = Membership.new
  end

  def create
    @membership = Membership.new(membership_params)

    @membership.project_id = params[:project_id]

    if @membership.save
      redirect_to project_memberships_path(@project), notice: "#{User.find(@membership.user_id).full_name} was successfully added."
    else
      render :index
    end
  end

  def update
    if @membership.update(membership_params)
      redirect_to project_memberships_path(@project), notice: "#{User.find(@membership.user_id).full_name} was successfully updated."
    else
      render :index
    end
  end

  def destroy
    if (@role_authentication && (@membership.user_id == current_user.id)) || (@membership.user_id == current_user.id)
      @membership.destroy
      redirect_to projects_path, notice: "#{@membership.user.first_name} #{@membership.user.last_name} was successfully removed."
    elsif @role_authentication
      @membership.destroy
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.first_name} #{@membership.user.last_name} was successfully removed."
    else
      redirect_to projects_path, alert: "You do not have access."
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_membership
      @membership = Membership.find(params[:id])
    end

    def membership_params
      params.require(:membership).permit(:role, :user_id, :project_id)
    end

    def authenticate
      redirect_to '/signin' unless current_user
      if !current_user
        flash[:alert] = "You must sign in first."
      end
    end

    def check_last_owner
      if @membership.role == "Owner" && @project.memberships.find_all{|membership| membership.role == "Owner"}.count == 1
        flash[:membership] = "Projects must have at least one owner."
        redirect_to project_memberships_path(@project)
      end
    end

    def remove_action_authentication
      @role_authentication = @project.users.map{|user| (user.id == current_user.id)} && (@project.memberships.find{|hash| (hash["project_id"] == @project.id) && (hash["user_id"] == current_user.id) && (hash["role"] == "Owner")}) || current_user.admin
      @member_authentication = @project.users.include?(current_user) || current_user.admin
    end

    def role_authentication
      unless @role_authentication
        redirect_to project_memberships_path(@project), alert: "You do not have access."
      end
    end

    def member_authentication
      unless @member_authentication
        redirect_to projects_path, alert: "You do not have access."
      end
    end

end

app/views/memberships/_edit_form.html.erb
<table>
  <tbody>
    <% @project.memberships.each do |m| %>
      <% @membership = Membership.find(m.id) %>

      <div class = "col-md-12">
      </div>

      <%= form_for [@project,@membership] do |f| %>
        <tr class = "membership-form">
          <td class = "form-inline"><%= link_to User.find(@membership.user_id).full_name, user_path(@membership.user_id) %>&nbsp;&nbsp;</td>
          <td class = "form-inline"><%= f.select :role, [["Owner"],["Member"]], {include_blank: false}, {class: "form-control"} %>&nbsp;&nbsp;</td>
          <td class = "form-inline"><%= f.submit "Update", class: "btn btn-primary" %>&nbsp;&nbsp;</td>
          <% if @project.memberships.find_all{|membership| membership.role == "Owner"}.count == 1 && @membership.role == "Owner" %>
            <% if @membership.user_id == current_user.id %>
              <td class = "form-inline">You are the last owner</td>
            <% else %>
              <td class = "form-inline">They are the last owner</td>
            <% end %>
          <% else %>
            <td class = "form-inline"><%= link_to '<i class="glyphicon glyphicon-remove" aria-hidden="true"></i>'.html_safe, project_membership_path(@project,@membership), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
      
    <% end %>
  </tbody>
</table>

app/views/memberships/_error.html.erb
<% @count = 0 %>
<% flash.each do |type, message| %>
  <% if type == "membership" %>
    <% @last_owner_error = true %>
    <% @count = 1 %>
  <% end %>
<% end %>

<% if @membership.errors.any? || @last_owner_error %>
  <div class = "alert alert-danger" id="error-explanation">
    <h4><%= pluralize((@membership.errors.count + @count), "error") %> prohibited this task from being saved:</h4>
    <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <% flash.each do |type, message| %>
        <% if type == "membership" %>
          <li><%= message %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/memberships/_form.html.erb
<div class = "col-md-12">
</div>

<%= form_for [@project,@membership], html: {class: "well form-inline"} do |f| %>

  <div class = "form-group">
    <div class = "form-controls">
      <%= f.collection_select :user_id, User.order(:last_name), :id, :full_name, {include_blank: "Please select a user..."}, {class: "form-control"} %>
    </div>
  </div>

  <div class = "form-group">
    <div class = "form-controls">
      <%= f.select :role, [["Owner"],["Member"]], {include_blank: "Membership"}, {class: "form-control"} %>
    </div>
  </div>

  <div class = "form-group">
    <div>
      <%= f.submit "Add New Member", class: "btn btn-primary" %>
    </div>
  </div>

<% end %>

app/views/memberships/_membership_listing.html.erb
<table class = "table">
  <thead>
    <tr>
      <th>User Name</th>
      <th>Project Role</th>
      <th>Delete Membership?</th>
    </tr>
  </thead>

  <tbody>
    <% @project.memberships.each do |m| %>
      <% @membership = Membership.find(m.id) %>
      <tr>
        <td><%= link_to User.find(@membership.user_id).full_name, user_path(@membership.user_id) %></td>
        <td><%= @membership.role %></td>
        <% if @membership.user_id == current_user.id %>
          <td>
            <%= link_to '<i class="glyphicon glyphicon-remove" aria-hidden="true"></i>'.html_safe, project_membership_path(@project,@membership), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/memberships/index.html.erb
<div class = "page-header">
  <h1><%= @project.name %>: Manage Members</h1>
</div>

<ol class = "breadcrumb">
  <li><a href = "/projects">Projects</a></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class = "active">Memberships</li>
</ol>

<%= render 'error' %>

<% if @role_authentication %>
  <%= render 'form' %>
<% end %>
      
<% if @role_authentication %>
  <%= render 'edit_form' %>
<% else %>
  <%= render 'membership_listing' %>
<% end %>