config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  root 'welcome#index'
    get '/about' => 'about#index'
    # get '/terms' => 'terms#index'
    get '/faq' => 'faq#index'
    get '/tasks' => 'tasks#index'
    get '/users' => 'users#index'
    get '/projects' => 'projects#index'
    get '/projects/:id/noaccess' => 'projects#redirect_for_non_member'

    get '/signup' => 'registrations#new'
    post '/signup' => 'registrations#create'

    get '/signin' => 'sessions#new'
    post '/signin' => 'sessions#create'

    get '/signout' => 'sessions#destroy'

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :comments, :dependent => :destroy

  validates :description, presence: true
  validates :project_id, presence: true

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  before_action :member_authentication

  def index
    @tasks = []
    Task.all.each do |task|
      if task.project_id == @project.id
        @tasks << task
      end
    end
  end

  def show
    @comment = Comment.new
    @comments = @task.comments
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    @task.project_id = params[:project_id]

    if @task.save
      redirect_to project_tasks_path(@project), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    old_attrs = @task.attributes
    if @task.update(task_params)
      redirect_to project_tasks_path(@project), notice: 'Task was successfully updated.'
    else
      # replace blank attributes with old params
      new_attrs = {}
      @task.attributes.each do |attr, val|
        if @task.errors.added? attr, :blank
          new_attrs[attr] = old_attrs[attr]
        end
      end
      @task.assign_attributes(new_attrs)
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.'
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def task_params
      params.require(:task).permit(:description, :task_due_date, :task_completed)
    end

    def authenticate
      redirect_to '/signin' unless current_user
      if !current_user
        flash[:alert] = "You must sign in first."
      end
    end

    def member_authentication
      unless @project.users.include?(current_user) || current_user.admin
        redirect_to projects_path, alert: "You do not have access."
      end
    end

end

app/views/tasks/_form.html.erb
<%= render partial: 'shared/error', locals: { object: @task } %>

<div class = "col-md-12">
</div>

<%= form_for [@project, @task], html: {class: "form-horizontal"} do |f| %>
  <div class= "form-group">
    <%= f.label :description, class: "control-label col-md-2" %>
    <div class = "form-controls col-md-4">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class = "form-group">
    <%= f.label :task_due_date, "Due Date", class: "control-label col-md-2" %>
    <div class = "form-controls col-md-4">
      <%= f.date_select :task_due_date, class: "form-control" %>
    </div>
  </div>

  <% if @task.new_record? %>
    <div class = "form-group">
      <div class = "col-md-offset-2 col-md-4">
        <%= f.submit "Create Task", class: "btn btn-primary" %>
        <%= link_to "Cancel", project_tasks_path(@project), class: "btn btn-default" %>
      </div>
    </div>
  <% else %>
    <div class = "form-group">
      <%= f.label :task_completed, "Completed", class: "control-label col-md-2" %>
      <div class = "form-controls col-md-4">
        <%= f.check_box :task_completed %>
      </div>
    </div>
    <div class = "form-group">
      <div class = "col-md-offset-2 col-md-4">
        <%= f.submit "Update Task", class: "btn btn-primary" %>
        <%= link_to "Cancel", project_tasks_path(@project), class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<div class = "page-header">
  <h1>Editing Task</h1>
</div>

<ol class = "breadcrumb">
  <li><a href = "/projects">Projects</a></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li><%= link_to @task.description, project_task_path(@project,@task) %></li>
  <li class = "active">Edit</li>
</ol>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class = "page-header">
  <div class = "pull-right">
    <%= link_to 'New Task', new_project_task_path(@project), class: "btn btn-info" %>
  </div>
  <h1>Tasks for <%= @project.name %></h1>
</div>

<ol class = "breadcrumb">
  <li><a href = "/projects">Projects</a></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class = "active">Tasks</li>
</ol>

<table class = "table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Complete</th>
      <th>Due Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td>
          <%= link_to task.description, project_task_path(@project, task) %>
          &nbsp;&nbsp;<span class = "badge"><%= task.comments.count %></span>
        </td>
        <td><%= task.task_completed %></td>
        <td><%= task.task_due_date %></td>
        <td class = "text-right">
          <%= link_to "Edit", edit_project_task_path(@project, task), class: "btn btn-info" %>
          <%= link_to '<i class="glyphicon glyphicon-remove" aria-hidden="true"></i>'.html_safe, project_task_path(@project,task), method: :delete, data: { confirm: 'Are you sure?' }, id: "task_delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<div class = "page-header">
  <h1>New Task</h1>
</div>

<ol class = "breadcrumb">
  <li><a href = "/projects">Projects</a></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class = "active">New Task</li>
</ol>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class = "page-header">
  <div class = "pull-right">
    <%= link_to 'Edit', edit_project_task_path(@project, @task), class: "btn btn-info" %>
  </div>
  <h1><%= @task.description %></h1>
</div>

<ol class = "breadcrumb">
  <li><a href = "/projects">Projects</a></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
  <li class = "active"><%= @task.description %></li>
</ol>

<p>
  <strong>Due On:</strong> <%= @task.task_due_date %><br />
  <strong>Complete:</strong>
    <% if !(@task.task_completed) %>
      <%= "No" %>
    <% else %>
      <%= "Yes" %>
    <% end %>
</p>

<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div class = "row">
    <div class = "col-md-3">
      <% if comment.user == nil %>
        <span>Deleted User</span>
      <% else %>
        <span id = "username_comment"><%= link_to comment.user.full_name, user_path(comment.user) %></span>
      <% end %>
      <p class = "text-muted"><%= time_ago_in_words(comment.created_at) %> ago</p>
    </div>
    <div class = "col-md-9">
      <%= comment.description %>
    </div>
  </div>
<% end %>
<%= form_for [@project,@task,@comment], html: {class: "form-horizontal"} do |f| %>
  <div class = "form-group">
    <div class = "form-controls col-md-offset-3 col-md-6">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class = "form-group">
    <div class = "col-md-offset-3 col-md-4">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>