config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  root 'welcome#index'
    get '/about' => 'about#index'
    # get '/terms' => 'terms#index'
    get '/faq' => 'faq#index'
    get '/tasks' => 'tasks#index'
    get '/users' => 'users#index'
    get '/projects' => 'projects#index'
    get '/projects/:id/noaccess' => 'projects#redirect_for_non_member'

    get '/signup' => 'registrations#new'
    post '/signup' => 'registrations#create'

    get '/signin' => 'sessions#new'
    post '/signin' => 'sessions#create'

    get '/signout' => 'sessions#destroy'

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, :dependent => :destroy
  has_many :memberships, :dependent => :destroy
  has_many :users, through: :memberships

  validates :name, presence: true

  def task_count
    if tasks.count == 1
      "#{tasks.count} Task"
    else
      "#{tasks.count} Tasks"
    end
  end

  def membership_count
    if memberships.count == 1
      "#{memberships.count} Member"
    else
      "#{memberships.count} Members"
    end
  end

  def task_count_lowercase
    if tasks.count == 1
      "#{tasks.count} task"
    else
      "#{tasks.count} tasks"
    end
  end

  def membership_count_lowercase
    if memberships.count == 1
      "#{memberships.count} membership"
    else
      "#{memberships.count} memberships"
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_params, only: [:show, :edit, :update, :destroy, :role_authentication, :redirect_for_non_member, :member_authentication]
  before_action :authenticate
  before_action :remove_action_authentication, only: [:show, :edit, :update, :destroy]
  before_action :role_authentication, only: [:edit, :update, :destroy]
  before_action :member_authentication, only: [:show]

  def index
    @projects = Project.all
    @filtered_projects = []
    @projects.each do |project|
      if current_user.admin
        @filtered_projects << {"#{project.id}": true}
      elsif project.users.include?(current_user)
        if (project.memberships.find{ |hash| (hash["project_id"] == project.id) && (hash["user_id"] == current_user.id) && (hash["role"] == "Owner")})
          @filtered_projects << {"#{project.id}": true}
        else
          @filtered_projects << {"#{project.id}": false}
        end
      end
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      @membership = Membership.create(project_id: @project.id, user_id: current_user.id, role: "Owner")
      redirect_to project_tasks_path(@project), notice: "Project was successfully created."
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    old_attrs = @project.attributes
    if @project.update(project_params)
      redirect_to @project, notice: "Project was successfully updated."
    else
      new_attrs = {}
      @project.attributes.each do |attr, val|
        if @project.errors.added? attr, :blank
          new_attrs[attr] = old_attrs[attr]
        end
      end
      @project.assign_attributes(new_attrs)
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: "Project was successfully destroyed."
  end

  def redirect_for_non_member
    redirect_to projects_path, alert: "You do not have access."
  end

  private

  def find_params
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end

  def authenticate
    redirect_to '/signin' unless current_user
    if !current_user
      flash[:alert] = "You must sign in first."
    end
  end

  def remove_action_authentication
    @role_authentication = @project.users.map{|user| (user.id == current_user.id)} && (@project.memberships.find{|hash| (hash["project_id"] == @project.id) && (hash["user_id"] == current_user.id) && (hash["role"] == "Owner")}) || current_user.admin
    @member_authentication = @project.users.include?(current_user) || current_user.admin
  end

  def role_authentication
    unless @role_authentication
      redirect_to @project, alert: "You do not have access."
    end
  end

  def member_authentication
    unless @member_authentication
      redirect_to projects_path, alert: "You do not have access."
    end
  end

end

app/views/projects/_form.html.erb
<%= render partial: 'shared/error', locals: { object: @project } %>

<div class = "col-md-12">
</div>

<%= form_for @project, html: {class: "form-horizontal"} do |f| %>
  <div class = "form-group">
    <%= f.label :name, "Name", class: "control-label col-md-2" %>
    <div class = "form-controls col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class = "form-group">
    <div class = "col-md-offset-2 col-md-4">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", projects_path, class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class = "page-header">
  <h1>Edit Project</h1>
</div>

<ol class = "breadcrumb">
  <li><a href = "/projects">Projects</a></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class = "active">Edit</li>
</ol>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class = "page-header">
  <div class = "pull-right" id = "new-project-button-div">
    <%= link_to 'New Project', new_project_path, class: "btn btn-info" %>
  </div>
  <h1>Projects</h1>
</div>

<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @filtered_projects.each do |row| %>
      <% row.each do |project_id, owner_boolean| %>
        <% project = Project.find(project_id.to_s.to_i) %>
        <tr>
          <td><%= link_to project.name, project %></td>
          <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
          <td class = "text-right">
            <% if owner_boolean %>
              <%= link_to 'Edit', edit_project_path(project), class: "btn btn-info" %>
              <%= link_to 'Delete', project, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class = "page-header">
  <h1>New Project</h1>
</div>

<ol class = "breadcrumb">
  <li><a href = "/projects">Projects</a></li>
  <li class = "active">New Project</li>
</ol>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class = "page-header">
  <% if @role_authentication %>
    <div class = "pull-right">
      <%= link_to "Edit", edit_project_path(@project), class: "btn btn-info" %>
    </div>
  <% end %>
  <h1><%= @project.name %></h1>
</div>

<ol class = "breadcrumb">
  <li><a href = "/projects">Projects</a></li>
  <li class = "active"><%= @project.name %></li>
</ol>

<dl class = "dl-horizontal">
  <dt></dt>
  <dd><h4><%= link_to @project.task_count, project_tasks_path(@project) %></h4></dd>
  <dt></dt>
  <dd><h4><%= link_to @project.membership_count, project_memberships_path(@project) %></h4></dd>
</dl>

<% if @role_authentication %>
  <div class = "well">
    <h4>Delete Project</h4>
    <p>Deleting this project will also delete <%= @project.membership_count_lowercase %>, <%= @project.task_count_lowercase %> and associated comments.</p>
    <%= link_to 'Delete', @project, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>