config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  root 'welcome#index'
    get '/about' => 'about#index'
    # get '/terms' => 'terms#index'
    get '/faq' => 'faq#index'
    get '/tasks' => 'tasks#index'
    get '/users' => 'users#index'
    get '/projects' => 'projects#index'
    get '/projects/:id/noaccess' => 'projects#redirect_for_non_member'

    get '/signup' => 'registrations#new'
    post '/signup' => 'registrations#create'

    get '/signin' => 'sessions#new'
    post '/signin' => 'sessions#create'

    get '/signout' => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= favicon_link_tag 'favicon.ico' %>

    <title>Task-Me</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

  </head>

  <body id = "top">
    <div class = "navbar navbar-default navbar-fixed-top" role = "navigation">
      <div class = "container">
        <div class = "navbar-header">
          <% if !marketing_page %>
            <%= link_to "Task-Me", projects_path, class: "navbar-brand" %>
          <% else %>
            <%= link_to "Task-Me", root_path, class: "navbar-brand" %>
          <% end %>
        </div>
        <% if !marketing_page %>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projects <span class = "caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% project_dropdown.each do |project| %>
                  <li><%= link_to "#{project.name}", project_path(project) %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "New Project", new_project_path %></li>
              </ul>
            </li>
            <li><%= link_to "Users", users_path %></li>
          </ul>
        <% end %>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to current_user.full_name, user_path(current_user) %></li>
            <li><%= link_to "Sign Out", signout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class = "container">

      <% flash.each do |type, message| %>
        <% if type == "notice" %>
        <b>
          <center>
            <div class="alert alert-success">
              <%= message %>
            </div>
          </center>
        </b>
        <% elsif type == "alert" %>
        <b>
          <center>
            <div class="alert alert-danger">
              <%= message %>
            </div>
          </center>
        </b>
        <% end %>
      <% end %>

      <%= yield %>


        <footer>
          <div class = "row">
            <% if !marketing_page %>
              <center><div class = "col-md-12">
                <%= link_to "Home", root_path %>
                |
                <%= link_to "About", about_path %>
                <!-- |
                <#%= link_to "Terms", terms_path %> -->
                |
                <%= link_to "FAQ", faq_path %>
              </div></center>

            <% else %>
              <div class = "col-md-6">
                <%= link_to "About", about_path %>
                |
                <!-- <#%= link_to "Terms", terms_path %>
                | -->
                <%= link_to "FAQ", faq_path %>
                <% if current_user %>
                  |
                  <%= link_to "Users", users_path %>
                  |
                  <%= link_to "Projects", projects_path %>
                <% end %>
              </div>

              <div class = "col-md-6 text-right">
                <a href = "https://www.linkedin.com/in/daniellemullane" target = "_blank">
                  <%= image_tag "linked_in-f852478f8950eb3fca3367cb545aaa52.jpg", alt: "LinkedIn", class: "img-footer", width: "28", height: "25" %>
                </a>

                <a href = "https://github.com/demullane" target = "_blank">
                  <%= image_tag "GitHub-de8164cc6a609537cfdab331e002ebb3.png", alt: "GitHub", class: "img-footer", width: "28", height: "28" %>
                </a>

                <a href = "https://twitter.com/demullane" target = "_blank">
                  <%= image_tag "Twitter-0c8c529fb7181e05ab5c30416e3a70fa.png", alt: "Twitter", class: "img-footer", width: "28", height: "23" %>
                </a>

                <a href = "https://students.gschool.it/cohorts/9/students/202" target = "_blank">
                  <%= image_tag "galvanize-g-b3da24895ed7d4fd33c43d9226c16242.png", alt: "Galvanize g", class: "img-footer", width: "16", height: "28" %>
                </a>
              </div>
            <% end %>

          </div>
        </footer>

    </div>
  </body>
</html>